#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Oct 03, 2023 08:07:49 PM +0800  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)

import UIhw3_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran:
       return
    style = ttk.Style()
    if sys.platform == "win32":
       style.theme_use('winnative')
    style.configure('.',background=_bgcolor)
    style.configure('.',foreground=_fgcolor)
    style.configure('.',font='TkDefaultFont')
    style.map('.',background =
       [('selected', _compcolor), ('active',_ana2color)])
    if _bgmode == 'dark':
       style.map('.',foreground =
         [('selected', 'white'), ('active','white')])
    else:
       style.map('.',foreground =
         [('selected', 'black'), ('active','black')])
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1046x888+429+89")
        top.minsize(124, 1)
        top.maxsize(1924, 1061)
        top.resizable(0,  0)
        top.title("NNhomework3(112522101)")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top
        self.l1 = tk.StringVar()
        self.l2 = tk.StringVar()
        self.c1 = tk.IntVar()

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=-0.293, rely=0.837, height=48, width=84)
        self.Button1.configure(activebackground="beige")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=UIhw3_support.btn1)
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Button''')
        _style_code()
        self.TLabel1 = ttk.Label(self.top)
        self.TLabel1.place(relx=0.163, rely=0.637, height=55, width=783)
        self.TLabel1.configure(background="#d9d9d9")
        self.TLabel1.configure(foreground="#000000")
        self.TLabel1.configure(font="TkDefaultFont")
        self.TLabel1.configure(relief="flat")
        self.TLabel1.configure(anchor='w')
        self.TLabel1.configure(justify='left')
        self.TLabel1.configure(text='''...''')
        self.TLabel1.configure(textvariable=self.l1)
        self.l1.set('''...''')
        self.TLabel1.configure(compound='left')
        self.TLabel1.configure(cursor="fleur")
        self.TLabel2 = ttk.Label(self.top)
        self.TLabel2.place(relx=0.163, rely=0.742, height=55, width=783)
        self.TLabel2.configure(background="#d9d9d9")
        self.TLabel2.configure(foreground="#000000")
        self.TLabel2.configure(font="TkDefaultFont")
        self.TLabel2.configure(relief="flat")
        self.TLabel2.configure(anchor='w')
        self.TLabel2.configure(justify='left')
        self.TLabel2.configure(text='''...''')
        self.TLabel2.configure(textvariable=self.l2)
        self.l2.set('''...''')
        self.TLabel2.configure(compound='left')
        self.TLabel2.configure(cursor="fleur")

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.038, rely=0.642, height=48, width=104)
        self.Button2.configure(activebackground="beige")
        self.Button2.configure(activeforeground="black")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(command=UIhw3_support.datasetbtn)
        self.Button2.configure(compound='left')
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Train Data''')
        self.Button3 = tk.Button(self.top)
        self.Button3.place(relx=0.038, rely=0.742, height=48, width=104)
        self.Button3.configure(activebackground="beige")
        self.Button3.configure(activeforeground="black")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(command=UIhw3_support.datasetbtn2)
        self.Button3.configure(compound='left')
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Test Data''')

        self.Button4 = tk.Button(self.top)
        self.Button4.place(relx=0.552, rely=0.621, height=88, width=124)
        self.Button4.configure(activebackground="beige")
        self.Button4.configure(activeforeground="black")
        self.Button4.configure(background="#d9d9d9")
        self.Button4.configure(command=UIhw3_support.testbtn1)
        self.Button4.configure(compound='left')
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''Prev''')
        self.Button5 = tk.Button(self.top)
        self.Button5.place(relx=0.702, rely=0.621, height=88, width=124)
        self.Button5.configure(activebackground="beige")
        self.Button5.configure(activeforeground="black")
        self.Button5.configure(background="#d9d9d9")
        self.Button5.configure(command=UIhw3_support.testbtn2)
        self.Button5.configure(compound='left')
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0")
        self.Button5.configure(text='''Next''')

        self.Button6 = tk.Button(self.top)
        self.Button6.place(relx=0.622, rely=0.751, height=88, width=124)
        self.Button6.configure(activebackground="beige")
        self.Button6.configure(activeforeground="black")
        self.Button6.configure(background="#d9d9d9")
        self.Button6.configure(command=UIhw3_support.startbtn1)
        self.Button6.configure(compound='left')
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(pady="0")
        self.Button6.configure(text='''Start''')

        self.check_btn1 = tk.Checkbutton(self.top)
        self.check_btn1.place(relx=0.038, rely=0.832)
        self.check_btn1.configure(variable=self.c1)
        self.check_btn1.configure(activebackground="beige")
        self.check_btn1.configure(activeforeground="black")
        self.check_btn1.configure(background="#d9d9d9")
        self.check_btn1.configure(compound='left')
        self.check_btn1.configure(disabledforeground="#a3a3a3")
        self.check_btn1.configure(foreground="#000000")
        self.check_btn1.configure(highlightbackground="#d9d9d9")
        self.check_btn1.configure(highlightcolor="black")
        self.check_btn1.configure(pady="0")
        self.check_btn1.configure(text='''Add noise''')

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.018, rely=0.1, relheight=0.467, relwidth=0.972)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")

def start_up():
    UIhw3_support.main()

if __name__ == '__main__':
    UIhw3_support.main()




