#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Oct 02, 2023 11:16:51 PM +0800  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
from tkinter import filedialog
import UIhw2
import simple_playground

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.quit)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = UIhw2.Toplevel1(_top1)
    _top1.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    root.mainloop()

def btn1(*args):
    if _debug:
        print('unknown_support.btn1')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

def datasetbtn(*args):
    if _debug:
        file_path = filedialog.askopenfilename()   # 選擇檔案後回傳檔案路徑與名稱
        _w1.l1.set(file_path)
        _w1.Button3['state'] = tk.NORMAL
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

def epochbtn(*args):
    if _debug:
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

def lrbtn(*args):
    if _debug:
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

def trainbtn(*args):
    if _debug:
        #獲取路徑、epoch、k的數據
        path = str(_w1.l1.get())
        k = int(_w1.Spinbox1.get())
        epoch = int(_w1.Spinbox2.get())
        #呼叫程式
        simple_playground.run_example(path,k,epoch)
        _w1.Button3['state'] = tk.NORMAL
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

if __name__ == '__main__':
    UIhw2.start_up()




